# Generated by Django 4.0 on 2022-03-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folio', '0004_message_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gh_links',
            field=models.URLField(blank=True, null=True),
        ),
    ]
